### ISSUE TITLE
Champs de la base de données

### ISSUE THREAD

**Issue by PierreSylvain** [MirkoV1987/OCR-P5#19]
Table **comment**
- changer date_creation par date_add
- AUTO INCREMENT sur le champ id
- changer disabled par active

Table **post**
- changer chapo par chapeau
- changer date_creation par date_add

Table **user**
- changer la taille du champ email en 254 
- changer le type password en text
- changer activated par active
- changer userType par role et changer le type en int
- changer date_creation par date_add

**Comment by MirkoV1987** [comment]
Fix #19 db table changes

**Comment by MirkoV1987** [comment]
Base de données terminée
